urlPrefix: admin
port: 8080
auth:
  type: inConfig
  jwtSecret: test123
  details:
    - name: test
      pass: test

sources:
  main:
    driver: mysql
    host: "localhost"
    port: 3309
    user: "test"
    pass: "test"
    name: "test"
    SSLMode: "disable"
